---

- name: Add Redis to the sources list
  apt_repository:
    repo: ppa:rwky/redis
  register: last_result
  tags: packages

- name: Install Redis
  apt:
    name: redis
    force: yes
    state: latest
    update_cache: "{{ 'yes' if last_result.changed else 'no'}}"
  tags: packages

- name: Ensure that the Redis service is running
  service: name=redis state=started enabled=yes
  tags: packages