language: python
python:
  - "2.7"
services:
  - postgresql
  - rabbitmq
install: 
  - pip install -r reqs/prod.txt
env:
  - DJANGO_SETTINGS_MODULE="djangus.settings.travis" DJANGUS_SECRET_KEY="totallynotmyrealsecretkey"
before_script:
  - psql -c 'create database djangus;' -U postgres
  - python manage.py syncdb --noinput
script: test