language: python
sudo: false
python:
  - "2.7"
  - "3.4"
services:
  - postgresql
  - rabbitmq
  - memcached
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq gcc-4.8 g++-4.8 libstdc++-4.8-dev
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20
  - pip install -r reqs/travis.txt
env:
  global:
    - DJANGO_SETTINGS_MODULE="bongo.settings.travis"
    - BONGO_SECRET_KEY="totallynotmyrealsecretkey"
    - BONGO_LOGENTRIES_TOKEN="nopenotreal"
    - BONGO_RAVEN_DSN="http://dd2c825ff9b1417d88a99573903ebf80:91631495b10b45f8a1cdbc492088da6a@localhost:9000/1"
    - secure: "fQbky6XqlOcEtd97/GNvOca7VK4n2cyV7USf+2Bt+aFC3LyZRyPSSYjjdxUBjeRheGhdov/sjxcpwWIEJ6lF/JxOjyv4ekEQBlLHk1q34pQxPmaYcJ6DOIm/U6Vv/IRyOtBizc3TqutLOzpLlfxdDr0SbGyM+EJbNBdb1tUrLNo="
    - secure: "rrGk1BvBIx5TZhHxrG/d8ClMcESzj0Y/puRiK0xZHFufdazaHiN5z9LLwrz+hM1K5FGQBYpgpCEwUekRtHNPpVTJX4bzgdjeH/SrQmxwJWCIZeHLuqwtMpG03BxkcJxgtReXgSH5Ibfqc5AmRvyTapIGQLBDaYZp5ghzFfZGQNo="
before_script:
  - psql -c 'create database bongo_test;' -U postgres
  - python manage.py syncdb --noinput
  - python manage.py nltk-init
script:
  - coverage run --source=bongo manage.py test
after_success:
  - coveralls