language: python
sudo: false
python:
  - "2.7"
  - "3.4"
services:
  - postgresql
  - rabbitmq
  - memcached
install:
  - pip install -r reqs/travis.txt
env:
  global:
    - DJANGO_SETTINGS_MODULE="bongo.settings.travis"
    - DJANGO_SECRET_KEY="totallynotmyrealsecretkey"
    - RAVEN_DSN="http://dd2c825ff9b1417d88a99573903ebf80:91631495b10b45f8a1cdbc492088da6a@localhost:9000/1"
    - secure: "fQbky6XqlOcEtd97/GNvOca7VK4n2cyV7USf+2Bt+aFC3LyZRyPSSYjjdxUBjeRheGhdov/sjxcpwWIEJ6lF/JxOjyv4ekEQBlLHk1q34pQxPmaYcJ6DOIm/U6Vv/IRyOtBizc3TqutLOzpLlfxdDr0SbGyM+EJbNBdb1tUrLNo="
    - secure: "rrGk1BvBIx5TZhHxrG/d8ClMcESzj0Y/puRiK0xZHFufdazaHiN5z9LLwrz+hM1K5FGQBYpgpCEwUekRtHNPpVTJX4bzgdjeH/SrQmxwJWCIZeHLuqwtMpG03BxkcJxgtReXgSH5Ibfqc5AmRvyTapIGQLBDaYZp5ghzFfZGQNo="
    - secure: "GnHGbcPj2rxWpH6/8yRcoEOA7XckztgyHGFEo4IE4QEraDye7r/7ANCwlKgL2S1IOUjyFdk/BVA16PUXaF7wTQmgO2p24ZEis12lCTnUA9WdZv214/zzuNEvlaHcpBy7Ne8bGMZsZ2ZOrGEeTzkUXNh10+3IgHeFs5fthCjG7SI="
    - secure: "HpEzCKwwkl59GkqqcP7lkdgVgokPvBgQCBwiI7nf4N2aeQvkkXZAB3KbElhSgI1TV5E/Xgm9tgWteJgNPFYg0JTsSzSD0sl27b3X1xArCm1Z4dUtS7GeV4NYHcTjalSwhuleXtwEwcVMQPJdrCyKAMvxaKiC3fp28TUnfIdW890="
    - secure: "eFFNukDzwA76RzB/HZqU0aVGHa8lZBq01uLiMzu6/z442nxUl+8DW9AhT+cB7ujwJc2VRmEaclAs3FYWs/tXaw1kq4QwsjIRSJZj1n5733nGbqI3KO7LhEuJA8paZTFFy6LANJB/6Xly+5C9vwSvCoXMbb8hdlNIvT1O7tSfNmI="
before_script:
  - psql -c 'create database bongo_test;' -U postgres
  - python manage.py syncdb --noinput
  - python manage.py nltk-init
script:
  - coverage run --source=bongo manage.py test
after_success:
  - coveralls