language: python
python:
  - "2.7"
services:
  - postgresql
  - rabbitmq
install: 
  - pip install -r reqs/travis.txt
env:
  - DJANGO_SETTINGS_MODULE="bongo.settings.travis" DJANGUS_SECRET_KEY="totallynotmyrealsecretkey"
before_script:
  - psql -c 'create database bongo;' -U postgres
  - python manage.py syncdb --noinput
script: 
  - coverage run --source=bongo manage.py test
after_success:
  - coveralls