---

- name: Get name of most recent database backup from S3
  shell: "executable=/bin/bash AWS_ACCESS_KEY_ID={{ aws_access_key_id }} AWS_SECRET_ACCESS_KEY={{ aws_secret_access_key }} aws s3 ls bowdoinorient-bonus | grep .sql.gz | tail -1 | grep -oE '[^ ]+$'"
  register: archive_name
  tags: mysql_populate
  when: restore_mysql

- name: Download the database backup
  s3:
    aws_access_key: "{{ aws_access_key_id }}"
    aws_secret_key: "{{ aws_secret_access_key }}"
    bucket: bowdoinorient-bonus
    mode: get
    dest: /tmp/{{ archive_name.stdout }}
    object: "{{ archive_name.stdout }}"
  tags: mysql_populate
  when: restore_mysql

- name: Unzip database backup
  shell: "gunzip -c --force /tmp/{{ archive_name.stdout }} > /tmp/DB02Orient.sql"
  tags: mysql_populate
  when: restore_mysql

- name: Pipe the unzipped database backup to mysql
  shell: "mysql -uroot -p{{ mysql_root_password }} {{ legacy_db_name }} < /tmp/DB02Orient.sql"
  tags: mysql_populate
  when: restore_mysql
