---

- include: create_users_and_groups.yml

- include: setup_virtualenv.yml

- include: setup_git_repo.yml

- include: setup_django_app.yml

- include: setup_database.yml

- include: setup_newrelic.yml

- include: setup_supervisor.yml

- include: set_file_permissions.yml

- include: setup_nginx.yml