---

- name: Create a .ssh directory for root
  when: code_source == "git"
  file: path=/root/.ssh state=directory
  tags: git

- name: Create the SSH public key file
  copy:
    content: "{{ git_ssh_pub_key }}"
    dest: /root/.ssh/id_rsa.pub
    mode: 0644
  when: code_source == "git"
  tags: git

- name: Create the SSH private key file
  copy:
    content: "{{ git_ssh_priv_key }}"
    dest: /root/.ssh/id_rsa
    mode: 0600
  when: code_source == "git"
  tags: git

- name: Setup the Git repo
  git: repo={{ git_repo }} version={{ branch }} dest={{ project_path }} accept_hostkey=yes
  when: code_source == "git"
  tags: git

- name: Copy code from local machine using rsync
  when: code_source == "rsync"
  copy: src=../../../../
        dest={{ project_path }}
        force=yes
        owner={{ gunicorn_user }}
        group={{ gunicorn_group }}

- name: Copy code using Vagrant shared folder
  when: code_source == "vagrant"
  command: rsync -a --owner={{ gunicorn_user }} --group={{ gunicorn_group }} /vagrant/ {{project_path}}