---

- name: Provision a {{ application_name }} server
  hosts: all
  sudo: yes
  remote_user: "{{ ssh_user }}"
  vars_files:
    - env_vars/base.yml
    - env_vars/secure.yml
  roles:
    - { role: swapfile, tags: ['swapfile'], when: swapon == true}
    - { role: base, tags: ['base'] }
    - { role: letsencrypt, tags: ['ssl'] }
    - { role: db, tags: ['db'] }
    - { role: memcached, tags: ['memcached'] }
    - { role: redis, tags: ['redis'] }
    - { role: web, tags: ['web'] }
    - { role: rq, tags: ['rq'] }
